version: "3"

services:
    api:
      container_name: app
      build: 
        context: .
        target: development
      volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
      ports:
        - "3000:3000" 
      restart: always   
      links: 
         - mysql  
    
      command: npm run dev

    mysql:
       container_name: mysql_database
       image: mysql
       ports:
         - "3305:3306"
       volumes:
         - ./sql-data/db:/var/lib/msyql 
         
       environment:
          - MYSQL_DATABASE=docker_compose_mysql
          - MYSQL_PASSWORD=3105060237
          - MYSQL_ROOT_PASSWORD=3105060237
          

      